export declare const fontH1Regular: string;
export declare const fontH1Bold: string;
export declare const fontH2Regular: string;
export declare const fontH2Bold: string;
export declare const fontH3Regular: string;
export declare const fontH3Bold: string;
export declare const fontH4Regular: string;
export declare const fontH4Bold: string;
export declare const fontH5Regular: string;
export declare const fontH5Bold: string;
export declare const fontH6Regular: string;
export declare const fontH6Bold: string;
export declare const fontSmallRegular: string;
export declare const fontSmallBold: string;
export declare const fontSmallestRegular: string;
export declare const fontSmallestBold: string;
export declare const fontBaseRegular: string;
export declare const fontBaseBold: string;
//# sourceMappingURL=styles.css.d.ts.map