export declare const primaryFont: string;
export declare const vars: {
    fonts: {
        $main: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $mono: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    fontSizes: {
        $xs: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $sm: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $base: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $md: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $lg: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $2xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $3xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $4xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $5xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $6xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $7xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $8xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $9xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $10xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $11xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $12xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    lineHeights: {
        $initial: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $normal: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $base: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $lg: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    fontWeights: {
        $light: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $normal: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $medium: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $semiBold: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $bold: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    radii: {
        0: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $xs: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $sm: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $md: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $lg: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $round: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    borderWidths: {
        $sm: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $md: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    shadows: {
        $1: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    sizes: {
        0: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $0: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $1: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $2: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $3: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $4: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $5: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $6: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $7: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $8: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $9: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $11: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $12: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $13: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $14: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $15: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $16: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $17: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $18: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $19: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $24: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $25: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $32: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $35: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $48: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $56: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $64: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $2xs: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $xs: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $sm: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $md: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $lg: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $2xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $3xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    contentWidth: {
        $maxContentWidth: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
    colors: {
        $primarySurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $primaryContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $primaryLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $primaryHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $primaryAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $primarySurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $primaryContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondarySurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondaryContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondaryLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondaryHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondaryAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondarySurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $secondaryContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiarySurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiaryContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiaryLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiaryHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiaryAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiarySurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $tertiaryContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $borderDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $borderSubtle: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $borderContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $layoutSurfaceDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $layoutSurfaceSubtle: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $layoutSurfaceCard: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $layoutSurfaceContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $layoutSurfaceOverlay: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoSurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoSurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $infoContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningSurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningSurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $warningContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeSurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeSurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $negativeContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveSurface: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveLowContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveHighContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveAccent: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveSurfaceInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $positiveContrastInverted: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $disabledContrast: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $background: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $foreground: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $neutral1: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $neutral2: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $neutral3: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $neutral4: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $neutral5: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $neutral6: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $white: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $black: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $gray100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $blue100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $pink100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $red100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $yellow100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $green100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple10: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple20: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple30: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple40: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple50: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple60: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple70: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple80: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple90: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        $purple100: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    };
};
export declare const darkThemeClass: string;
export type ColorType = 'primary' | 'secondary' | 'tertiary' | 'info' | 'positive' | 'warning' | 'negative';
//# sourceMappingURL=vars.css.d.ts.map