version: '3'
services:
  devnet:
    image: kadena/devnet@sha256:348cc81804a75b17ed77db50d51e39db0746af32a0ef794af4f24adf346aa572
    ports:
      - 8080:8080 # HTTP
      - 5432:5432 # Postgres
      - 9999:9999 # Info
      - 1789:1789 
    environment:
      - MINING_BATCH_PERIOD=0.05
      - MINING_CONFIRMATION_PERIOD=1
