version: '3'
services:
  devnet:
    image: kadena/devnet@sha256:4e2eb4d9955eeb751afd7a4fe4e525ec38e33a0dd8b40e26f0417efd7929446c
    ports:
      - 8080:8080 # HTTP
      - 5432:5432 # Postgres
      - 9999:9999 # Info
      - 1789:1789 
    environment:
      - MINING_BATCH_PERIOD=0.05
      - MINING_CONFIRMATION_PERIOD=1
