name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: false

      - name: Runner setup
        uses: ./.github/actions/runner-setup

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  e2e:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: false

      - name: Runner setup
        uses: ./.github/actions/runner-setup

      - name: Setup Kadena sandbox
        uses: ./.github/actions/sandbox

      - name: Build
        run: pnpm build:e2e

      - name: Build output
        run: ls -la spirekey/.next

      - name: Install browser
        run: pnpm --filter spirekey run install:chromium

      - name: End-to-end test
        run: pnpm test:e2e

      - name: Publish Report
        uses: ./.github/actions/publish-report
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT_DIR: 'spirekey/playwright-report/'