name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        show-progress: false
    
    - name: Runner setup
      uses: ./.github/actions/runner-setup
    
    - name: Build
      run: pnpm build
    
    - name: Test
      run: pnpm test
  
  e2e:
    #needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        show-progress: false
    
    - name: Runner setup
      uses: ./.github/actions/runner-setup
    
    - name: Setup Kadena sandbox
      uses: ./.github/actions/sandbox
    
    - name: Build
      run: pnpm build
      env: 
        NODE_ENV: test
        
    - name: Install browser
      run: pnpm install:chromium

    - name: End-to-end test
      run: pnpm test:e2e
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report/ # This is where index.html will be output
        keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
        user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
        user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
  
    